<a href="https://colab.research.google.com/github/Gh6if84vi/DataScience-Learning-/blob/main/Pandas_DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import numpy as np

# Creating DataFrame

In [6]:
#using lists
students_data=[[100,80,10],[90,70,7],[110,100,40],[80,50,2]]
data=pd.DataFrame(students_data,columns=["iq","marks","package"])
data

    iq  marks  package
0  100     80       10
1   90     70        7
2  110    100       40
3   80     50        2

In [7]:
#using dictionary
students_data={
    "iq":[100,90,110,80],
    "marks":[80,70,100,50],
    "package":[10,7,40,2]

}
data=pd.DataFrame(students_data)
data

    iq  marks  package
0  100     80       10
1   90     70        7
2  110    100       40
3   80     50        2

In [8]:
#using read_csv
data=pd.read_csv('Housing.csv')
data

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [9]:
ipl_data=pd.read_csv('ipl-matches.csv')
ipl_data

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

# DataFrame Attributes and Methods

In [10]:
#shape
print(ipl_data.shape)
print(data.shape)

(950, 20)
(545, 13)

In [11]:
#dtypes
print(ipl_data.dtypes)

ID                   int64
City                object
Date                object
Season              object
MatchNumber         object
Team1               object
Team2               object
Venue               object
TossWinner          object
TossDecision        object
SuperOver           object
WinningTeam         object
WonBy               object
Margin             float64
method              object
Player_of_Match     object
Team1Players        object
Team2Players        object
Umpire1             object
Umpire2             object
dtype: object

In [12]:
#index
print(ipl_data.index)

RangeIndex(start=0, stop=950, step=1)

In [13]:
#values
print(ipl_data.values)

[[1312200 'Ahmedabad' '2022-05-29' ...
  "['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pandya', 'DA Miller', 'R Tewatia', 'Rashid Khan', 'R Sai Kishore', 'LH Ferguson', 'Yash Dayal', 'Mohammed Shami']"
  'CB Gaffaney' 'Nitin Menon']
 [1312199 'Ahmedabad' '2022-05-27' ...
  "['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D Padikkal', 'SO Hetmyer', 'R Parag', 'R Ashwin', 'TA Boult', 'YS Chahal', 'M Prasidh Krishna', 'OC McCoy']"
  'CB Gaffaney' 'Nitin Menon']
 [1312198 'Kolkata' '2022-05-25' ...
  "['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda', 'MP Stoinis', 'E Lewis', 'KH Pandya', 'PVD Chameera', 'Mohsin Khan', 'Avesh Khan', 'Ravi Bishnoi']"
  'J Madanagopal' 'MA Gough']
 ...
 [335984 'Delhi' '2008-04-19' ...
  "['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif', 'DS Lehmann', 'RA Jadeja', 'M Rawat', 'D Salunkhe', 'SK Warne', 'SK Trivedi', 'MM Patel']"
  'Aleem Dar' 'GA Pratapkumar']
 [335983 'Chandigarh' '2008-04-19' ...
  "['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dhoni', 'SK Raina', 'JDP Oram', 'S Badrinath', 'Joginder Sharma', 'P Amarnath', 'MS Gony', 'M Muralitharan']"
  'MR Benson' 'SL Shastri']
 [335982 'Bangalore' '2008-04-18' ...
  "['SC Ganguly', 'BB McCullum', 'RT Ponting', 'DJ Hussey', 'Mohammad Hafeez', 'LR Shukla', 'WP Saha', 'AB Agarkar', 'AB Dinda', 'M Kartik', 'I Sharma']"
  'Asad Rauf' 'RE Koertzen']]

In [14]:
#columns
print(ipl_data.columns)

Index(['ID', 'City', 'Date', 'Season', 'MatchNumber', 'Team1', 'Team2',
       'Venue', 'TossWinner', 'TossDecision', 'SuperOver', 'WinningTeam',
       'WonBy', 'Margin', 'method', 'Player_of_Match', 'Team1Players',
       'Team2Players', 'Umpire1', 'Umpire2'],
      dtype='object')

In [15]:
#head and tail
print(ipl_data.head())
print(ipl_data.tail())

        ID       City        Date Season  MatchNumber  \
0  1312200  Ahmedabad  2022-05-29   2022        Final
1  1312199  Ahmedabad  2022-05-27   2022  Qualifier 2
2  1312198    Kolkata  2022-05-25   2022   Eliminator
3  1312197    Kolkata  2022-05-24   2022  Qualifier 1
4  1304116     Mumbai  2022-05-22   2022           70

                         Team1                 Team2  \
0             Rajasthan Royals        Gujarat Titans
1  Royal Challengers Bangalore      Rajasthan Royals
2  Royal Challengers Bangalore  Lucknow Super Giants
3             Rajasthan Royals        Gujarat Titans
4          Sunrisers Hyderabad          Punjab Kings

                              Venue            TossWinner TossDecision  \
0  Narendra Modi Stadium, Ahmedabad      Rajasthan Royals          bat
1  Narendra Modi Stadium, Ahmedabad      Rajasthan Royals        field
2             Eden Gardens, Kolkata  Lucknow Super Giants        field
3             Eden Gardens, Kolkata        Gujarat Titans        field
4          Wankhede Stadium, Mumbai   Sunrisers Hyderabad          bat

  SuperOver                  WinningTeam    WonBy  Margin method  \
0         N               Gujarat Titans  Wickets     7.0    NaN
1         N             Rajasthan Royals  Wickets     7.0    NaN
2         N  Royal Challengers Bangalore     Runs    14.0    NaN
3         N               Gujarat Titans  Wickets     7.0    NaN
4         N                 Punjab Kings  Wickets     5.0    NaN

  Player_of_Match                                       Team1Players  \
0       HH Pandya  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...
1      JC Buttler  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...
2      RM Patidar  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...
3       DA Miller  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...
4   Harpreet Brar  ['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...

                                        Team2Players        Umpire1  \
0  ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...    CB Gaffaney
1  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...    CB Gaffaney
2  ['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...  J Madanagopal
3  ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...   BNJ Oxenford
4  ['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...   AK Chaudhary

         Umpire2
0    Nitin Menon
1    Nitin Menon
2       MA Gough
3      VK Sharma
4  NA Patwardhan
         ID        City        Date   Season MatchNumber  \
945  335986     Kolkata  2008-04-20  2007/08           4
946  335985      Mumbai  2008-04-20  2007/08           5
947  335984       Delhi  2008-04-19  2007/08           3
948  335983  Chandigarh  2008-04-19  2007/08           2
949  335982   Bangalore  2008-04-18  2007/08           1

                           Team1                        Team2  \
945        Kolkata Knight Riders              Deccan Chargers
946               Mumbai Indians  Royal Challengers Bangalore
947             Delhi Daredevils             Rajasthan Royals
948              Kings XI Punjab          Chennai Super Kings
949  Royal Challengers Bangalore        Kolkata Knight Riders

                                          Venue                   TossWinner  \
945                                Eden Gardens              Deccan Chargers
946                            Wankhede Stadium               Mumbai Indians
947                            Feroz Shah Kotla             Rajasthan Royals
948  Punjab Cricket Association Stadium, Mohali          Chennai Super Kings
949                       M Chinnaswamy Stadium  Royal Challengers Bangalore

    TossDecision SuperOver                  WinningTeam    WonBy  Margin  \
945          bat         N        Kolkata Knight Riders  Wickets     5.0
946          bat         N  Royal Challengers Bangalore  Wickets     5.0
947          bat         N             Delhi Daredevils  Wickets     9.0
948          bat         N          Chennai Super Kings     Runs    33.0
949        field         N        Kolkata Knight Riders     Runs   140.0

    method Player_of_Match                                       Team1Players  \
945    NaN       DJ Hussey  ['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...
946    NaN      MV Boucher  ['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...
947    NaN     MF Maharoof  ['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...
948    NaN      MEK Hussey  ['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...
949    NaN     BB McCullum  ['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...

                                          Team2Players    Umpire1  \
945  ['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...  BF Bowden
946  ['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...   SJ Davis
947  ['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...  Aleem Dar
948  ['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...  MR Benson
949  ['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...  Asad Rauf

            Umpire2
945     K Hariharan
946       DJ Harper
947  GA Pratapkumar
948      SL Shastri
949     RE Koertzen

In [16]:
#sample
print(ipl_data.sample())

         ID  City        Date Season MatchNumber                        Team1  \
435  829819  Pune  2015-05-20   2015  Eliminator  Royal Challengers Bangalore

                Team2                                    Venue  \
435  Rajasthan Royals  Maharashtra Cricket Association Stadium

                      TossWinner TossDecision SuperOver  \
435  Royal Challengers Bangalore          bat         N

                     WinningTeam WonBy  Margin method Player_of_Match  \
435  Royal Challengers Bangalore  Runs    71.0    NaN  AB de Villiers

                                          Team1Players  \
435  ['CH Gayle', 'V Kohli', 'AB de Villiers', 'Man...

                                          Team2Players       Umpire1  \
435  ['AM Rahane', 'SR Watson', 'SV Samson', 'SPD S...  AK Chaudhary

           Umpire2
435  C Shamshuddin

In [17]:
#info
print(ipl_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    object
 2   Date             950 non-null    object
 3   Season           950 non-null    object
 4   MatchNumber      950 non-null    object
 5   Team1            950 non-null    object
 6   Team2            950 non-null    object
 7   Venue            950 non-null    object
 8   TossWinner       950 non-null    object
 9   TossDecision     950 non-null    object
 10  SuperOver        946 non-null    object
 11  WinningTeam      946 non-null    object
 12  WonBy            950 non-null    object
 13  Margin           932 non-null    float64
 14  method           19 non-null     object
 15  Player_of_Match  946 non-null    object
 16  Team1Players     950 non-null    object
 17  Team2Players     950 non-null    object
 18  Umpire1          950 non-null    object
 19  Umpire2          950 non-null    object
dtypes: float64(1), int64(1), object(18)
memory usage: 148.6+ KB
None

In [18]:
#describe
print(data.describe())

print(f"for ipl_data:\n {ipl_data.describe()}")

              price          area    bedrooms   bathrooms     stories  \
count  5.450000e+02    545.000000  545.000000  545.000000  545.000000
mean   4.766729e+06   5150.541284    2.965138    1.286239    1.805505
std    1.870440e+06   2170.141023    0.738064    0.502470    0.867492
min    1.750000e+06   1650.000000    1.000000    1.000000    1.000000
25%    3.430000e+06   3600.000000    2.000000    1.000000    1.000000
50%    4.340000e+06   4600.000000    3.000000    1.000000    2.000000
75%    5.740000e+06   6360.000000    3.000000    2.000000    2.000000
max    1.330000e+07  16200.000000    6.000000    4.000000    4.000000

          parking
count  545.000000
mean     0.693578
std      0.861586
min      0.000000
25%      0.000000
50%      0.000000
75%      1.000000
max      3.000000
for ipl_data:
                  ID      Margin
count  9.500000e+02  932.000000
mean   8.304852e+05   17.056867
std    3.375678e+05   21.633109
min    3.359820e+05    1.000000
25%    5.012612e+05    6.000000
50%    8.297380e+05    8.000000
75%    1.175372e+06   19.000000
max    1.312200e+06  146.000000

In [19]:
#isnull
print(ipl_data.isnull().sum())

ID                   0
City                51
Date                 0
Season               0
MatchNumber          0
Team1                0
Team2                0
Venue                0
TossWinner           0
TossDecision         0
SuperOver            4
WinningTeam          4
WonBy                0
Margin              18
method             931
Player_of_Match      4
Team1Players         0
Team2Players         0
Umpire1              0
Umpire2              0
dtype: int64

In [20]:
#duplicated
print(ipl_data.duplicated().sum())

0

In [21]:
#rename
print(ipl_data.rename(columns={"Season":"year"},inplace=True))
print(ipl_data)

None
          ID        City        Date     year  MatchNumber  \
0    1312200   Ahmedabad  2022-05-29     2022        Final
1    1312199   Ahmedabad  2022-05-27     2022  Qualifier 2
2    1312198     Kolkata  2022-05-25     2022   Eliminator
3    1312197     Kolkata  2022-05-24     2022  Qualifier 1
4    1304116      Mumbai  2022-05-22     2022           70
..       ...         ...         ...      ...          ...
945   335986     Kolkata  2008-04-20  2007/08            4
946   335985      Mumbai  2008-04-20  2007/08            5
947   335984       Delhi  2008-04-19  2007/08            3
948   335983  Chandigarh  2008-04-19  2007/08            2
949   335982   Bangalore  2008-04-18  2007/08            1

                           Team1                        Team2  \
0               Rajasthan Royals               Gujarat Titans
1    Royal Challengers Bangalore             Rajasthan Royals
2    Royal Challengers Bangalore         Lucknow Super Giants
3               Rajasthan Royals               Gujarat Titans
4            Sunrisers Hyderabad                 Punjab Kings
..                           ...                          ...
945        Kolkata Knight Riders              Deccan Chargers
946               Mumbai Indians  Royal Challengers Bangalore
947             Delhi Daredevils             Rajasthan Royals
948              Kings XI Punjab          Chennai Super Kings
949  Royal Challengers Bangalore        Kolkata Knight Riders

                                          Venue                   TossWinner  \
0              Narendra Modi Stadium, Ahmedabad             Rajasthan Royals
1              Narendra Modi Stadium, Ahmedabad             Rajasthan Royals
2                         Eden Gardens, Kolkata         Lucknow Super Giants
3                         Eden Gardens, Kolkata               Gujarat Titans
4                      Wankhede Stadium, Mumbai          Sunrisers Hyderabad
..                                          ...                          ...
945                                Eden Gardens              Deccan Chargers
946                            Wankhede Stadium               Mumbai Indians
947                            Feroz Shah Kotla             Rajasthan Royals
948  Punjab Cricket Association Stadium, Mohali          Chennai Super Kings
949                       M Chinnaswamy Stadium  Royal Challengers Bangalore

    TossDecision SuperOver                  WinningTeam    WonBy  Margin  \
0            bat         N               Gujarat Titans  Wickets     7.0
1          field         N             Rajasthan Royals  Wickets     7.0
2          field         N  Royal Challengers Bangalore     Runs    14.0
3          field         N               Gujarat Titans  Wickets     7.0
4            bat         N                 Punjab Kings  Wickets     5.0
..           ...       ...                          ...      ...     ...
945          bat         N        Kolkata Knight Riders  Wickets     5.0
946          bat         N  Royal Challengers Bangalore  Wickets     5.0
947          bat         N             Delhi Daredevils  Wickets     9.0
948          bat         N          Chennai Super Kings     Runs    33.0
949        field         N        Kolkata Knight Riders     Runs   140.0

    method Player_of_Match                                       Team1Players  \
0      NaN       HH Pandya  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...
1      NaN      JC Buttler  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...
2      NaN      RM Patidar  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...
3      NaN       DA Miller  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...
4      NaN   Harpreet Brar  ['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...
..     ...             ...                                                ...
945    NaN       DJ Hussey  ['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...
946    NaN      MV Boucher  ['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...
947    NaN     MF Maharoof  ['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...
948    NaN      MEK Hussey  ['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...
949    NaN     BB McCullum  ['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...

                                          Team2Players        Umpire1  \
0    ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...    CB Gaffaney
1    ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...    CB Gaffaney
2    ['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...  J Madanagopal
3    ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...   BNJ Oxenford
4    ['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...   AK Chaudhary
..                                                 ...            ...
945  ['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...      BF Bowden
946  ['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...       SJ Davis
947  ['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...      Aleem Dar
948  ['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...      MR Benson
949  ['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...      Asad Rauf

            Umpire2
0       Nitin Menon
1       Nitin Menon
2          MA Gough
3         VK Sharma
4     NA Patwardhan
..              ...
945     K Hariharan
946       DJ Harper
947  GA Pratapkumar
948      SL Shastri
949     RE Koertzen

[950 rows x 20 columns]

# Math Methods

In [22]:
#sum
print(data.sum())
print(data.sum(axis=0))

price                                                      2597867440
area                                                          2807045
bedrooms                                                         1616
bathrooms                                                         701
stories                                                           984
mainroad            yesyesyesyesyesyesyesyesyesyesyesyesyesyesyesy...
guestroom           nonononoyesnononoyesyesnoyesnonononoyesnoyesno...
basement            nonoyesyesyesyesnonoyesnoyesyesnononoyesyesnon...
hotwaterheating     nononononononononononoyesnoyesnonononononoyesn...
airconditioning     yesyesnoyesyesyesyesnoyesyesyesnoyesnononoyesy...
parking                                                           378
prefarea            yesnoyesyesnoyesyesnoyesyesyesnoyesnoyesnoyesn...
furnishingstatus    furnishedfurnishedsemi-furnishedfurnishedfurni...
dtype: object
price                                                      2597867440
area                                                          2807045
bedrooms                                                         1616
bathrooms                                                         701
stories                                                           984
mainroad            yesyesyesyesyesyesyesyesyesyesyesyesyesyesyesy...
guestroom           nonononoyesnononoyesyesnoyesnonononoyesnoyesno...
basement            nonoyesyesyesyesnonoyesnoyesyesnononoyesyesnon...
hotwaterheating     nononononononononononoyesnoyesnonononononoyesn...
airconditioning     yesyesnoyesyesyesyesnoyesyesyesnoyesnononoyesy...
parking                                                           378
prefarea            yesnoyesyesnoyesyesnoyesyesyesnoyesnoyesnoyesn...
furnishingstatus    furnishedfurnishedsemi-furnishedfurnishedfurni...
dtype: object

# Selecting cols from a DataFrame..

In [23]:
#single cols
print(data.columns)
print(data['price'])

print(data.price)

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='object')
0      13300000
1      12250000
2      12250000
3      12215000
4      11410000
         ...
540     1820000
541     1767150
542     1750000
543     1750000
544     1750000
Name: price, Length: 545, dtype: int64
0      13300000
1      12250000
2      12250000
3      12215000
4      11410000
         ...
540     1820000
541     1767150
542     1750000
543     1750000
544     1750000
Name: price, Length: 545, dtype: int64

In [24]:
#multiple cols
print(data[['price','area']])

        price  area
0    13300000  7420
1    12250000  8960
2    12250000  9960
3    12215000  7500
4    11410000  7420
..        ...   ...
540   1820000  3000
541   1767150  2400
542   1750000  3620
543   1750000  2910
544   1750000  3850

[545 rows x 2 columns]

# Accessing rows from DataFrame

.**iloc** - searches using index positions

**loc** - searches using index labels

In [25]:
# single row
print(data.iloc[0])

price                13300000
area                     7420
bedrooms                    4
bathrooms                   2
stories                     3
mainroad                  yes
guestroom                  no
basement                   no
hotwaterheating            no
airconditioning           yes
parking                     2
prefarea                  yes
furnishingstatus    furnished
Name: 0, dtype: object

In [26]:
#multiple row
print(data.iloc[0:15])
print(data.iloc[0:25:2])

       price   area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0   13300000   7420         4          2        3      yes        no       no
1   12250000   8960         4          4        4      yes        no       no
2   12250000   9960         3          2        2      yes        no      yes
3   12215000   7500         4          2        2      yes        no      yes
4   11410000   7420         4          1        2      yes       yes      yes
5   10850000   7500         3          3        1      yes        no      yes
6   10150000   8580         4          3        4      yes        no       no
7   10150000  16200         5          3        2      yes        no       no
8    9870000   8100         4          1        2      yes       yes      yes
9    9800000   5750         3          2        4      yes       yes       no
10   9800000  13200         3          1        2      yes        no      yes
11   9681000   6000         4          3        2      yes       yes      yes
12   9310000   6550         4          2        2      yes        no       no
13   9240000   3500         4          2        2      yes        no       no
14   9240000   7800         3          2        2      yes        no       no

   hotwaterheating airconditioning  parking prefarea furnishingstatus
0               no             yes        2      yes        furnished
1               no             yes        3       no        furnished
2               no              no        2      yes   semi-furnished
3               no             yes        3      yes        furnished
4               no             yes        2       no        furnished
5               no             yes        2      yes   semi-furnished
6               no             yes        2      yes   semi-furnished
7               no              no        0       no      unfurnished
8               no             yes        2      yes        furnished
9               no             yes        1      yes      unfurnished
10              no             yes        2      yes        furnished
11             yes              no        2       no   semi-furnished
12              no             yes        1      yes   semi-furnished
13             yes              no        2       no        furnished
14              no              no        0      yes   semi-furnished
       price   area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0   13300000   7420         4          2        3      yes        no       no
2   12250000   9960         3          2        2      yes        no      yes
4   11410000   7420         4          1        2      yes       yes      yes
6   10150000   8580         4          3        4      yes        no       no
8    9870000   8100         4          1        2      yes       yes      yes
10   9800000  13200         3          1        2      yes        no      yes
12   9310000   6550         4          2        2      yes        no       no
14   9240000   7800         3          2        2      yes        no       no
16   9100000   6600         4          2        2      yes       yes      yes
18   8890000   4600         3          2        2      yes       yes       no
20   8750000   4320         3          1        2      yes        no      yes
22   8645000   8050         3          1        1      yes       yes      yes
24   8575000   8800         3          2        2      yes        no       no

   hotwaterheating airconditioning  parking prefarea furnishingstatus
0               no             yes        2      yes        furnished
2               no              no        2      yes   semi-furnished
4               no             yes        2       no        furnished
6               no             yes        2      yes   semi-furnished
8               no             yes        2      yes        furnished
10              no             yes        2      yes        furnished
12              no             yes        1      yes   semi-furnished
14              no              no        0      yes   semi-furnished
16              no             yes        1      yes      unfurnished
18              no             yes        2       no        furnished
20             yes              no        2       no   semi-furnished
22              no             yes        1       no        furnished
24              no             yes        2       no        furnished

In [27]:
#using loc
print(data.loc[0])

price                13300000
area                     7420
bedrooms                    4
bathrooms                   2
stories                     3
mainroad                  yes
guestroom                  no
basement                   no
hotwaterheating            no
airconditioning           yes
parking                     2
prefarea                  yes
furnishingstatus    furnished
Name: 0, dtype: object

# ACCESSING BOTH ROWS AND COLUMNS

In [28]:
print(data.iloc[0:4,0:3])

      price  area  bedrooms
0  13300000  7420         4
1  12250000  8960         4
2  12250000  9960         3
3  12215000  7500         4

In [29]:
print(data.loc[0:3,['price','area','bedrooms']])

      price  area  bedrooms
0  13300000  7420         4
1  12250000  8960         4
2  12250000  9960         3
3  12215000  7500         4

# **Filtering DataFrame**

In [30]:
print(ipl_data.head(8))

        ID       City        Date  year  MatchNumber  \
0  1312200  Ahmedabad  2022-05-29  2022        Final
1  1312199  Ahmedabad  2022-05-27  2022  Qualifier 2
2  1312198    Kolkata  2022-05-25  2022   Eliminator
3  1312197    Kolkata  2022-05-24  2022  Qualifier 1
4  1304116     Mumbai  2022-05-22  2022           70
5  1304115     Mumbai  2022-05-21  2022           69
6  1304114     Mumbai  2022-05-20  2022           68
7  1304113     Mumbai  2022-05-19  2022           67

                         Team1                        Team2  \
0             Rajasthan Royals               Gujarat Titans
1  Royal Challengers Bangalore             Rajasthan Royals
2  Royal Challengers Bangalore         Lucknow Super Giants
3             Rajasthan Royals               Gujarat Titans
4          Sunrisers Hyderabad                 Punjab Kings
5               Delhi Capitals               Mumbai Indians
6          Chennai Super Kings             Rajasthan Royals
7               Gujarat Titans  Royal Challengers Bangalore

                              Venue            TossWinner TossDecision  \
0  Narendra Modi Stadium, Ahmedabad      Rajasthan Royals          bat
1  Narendra Modi Stadium, Ahmedabad      Rajasthan Royals        field
2             Eden Gardens, Kolkata  Lucknow Super Giants        field
3             Eden Gardens, Kolkata        Gujarat Titans        field
4          Wankhede Stadium, Mumbai   Sunrisers Hyderabad          bat
5          Wankhede Stadium, Mumbai        Mumbai Indians        field
6         Brabourne Stadium, Mumbai   Chennai Super Kings          bat
7          Wankhede Stadium, Mumbai        Gujarat Titans          bat

  SuperOver                  WinningTeam    WonBy  Margin method  \
0         N               Gujarat Titans  Wickets     7.0    NaN
1         N             Rajasthan Royals  Wickets     7.0    NaN
2         N  Royal Challengers Bangalore     Runs    14.0    NaN
3         N               Gujarat Titans  Wickets     7.0    NaN
4         N                 Punjab Kings  Wickets     5.0    NaN
5         N               Mumbai Indians  Wickets     5.0    NaN
6         N             Rajasthan Royals  Wickets     5.0    NaN
7         N  Royal Challengers Bangalore  Wickets     8.0    NaN

  Player_of_Match                                       Team1Players  \
0       HH Pandya  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...
1      JC Buttler  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...
2      RM Patidar  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...
3       DA Miller  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...
4   Harpreet Brar  ['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...
5       JJ Bumrah  ['PP Shaw', 'DA Warner', 'MR Marsh', 'RR Pant'...
6        R Ashwin  ['RD Gaikwad', 'DP Conway', 'MM Ali', 'N Jagad...
7         V Kohli  ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...

                                        Team2Players                Umpire1  \
0  ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...            CB Gaffaney
1  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...            CB Gaffaney
2  ['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...          J Madanagopal
3  ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...           BNJ Oxenford
4  ['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...           AK Chaudhary
5  ['Ishan Kishan', 'RG Sharma', 'D Brevis', 'Til...            Nitin Menon
6  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...            CB Gaffaney
7  ['V Kohli', 'F du Plessis', 'GJ Maxwell', 'KD ...  KN Ananthapadmanabhan

            Umpire2
0       Nitin Menon
1       Nitin Menon
2          MA Gough
3         VK Sharma
4     NA Patwardhan
5      Tapan Sharma
6     NA Patwardhan
7  GR Sadashiv Iyer

In [31]:
#find all the final winners
ipl_data[ipl_data['MatchNumber']=='Final']

,ID,City,Date,year,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
74,1254117,Dubai,2021-10-15,2021,Final,Chennai Super Kings,Kolkata Knight Riders,Dubai International Cricket Stadium,Kolkata Knight Riders,field,N,Chennai Super Kings,Runs,27.0,NaN,F du Plessis,"['RD Gaikwad', 'F du Plessis', 'RV Uthappa', '...","['Shubman Gill', 'VR Iyer', 'N Rana', 'SP Nari...",Nitin Menon,RK Illingworth
134,1237181,NaN,2020-11-10,2020/21,Final,Delhi Capitals,Mumbai Indians,Dubai International Cricket Stadium,Delhi Capitals,bat,N,Mumbai Indians,Wickets,5.0,NaN,TA Boult,"['MP Stoinis', 'S Dhawan', 'AM Rahane', 'SS Iy...","['RG Sharma', 'Q de Kock', 'SA Yadav', 'Ishan ...",CB Gaffaney,Nitin Menon
194,1181768,Hyderabad,2019-05-12,2019,Final,Mumbai Indians,Chennai Super Kings,Rajiv Gandhi International Stadium,Mumbai Indians,bat,N,Mumbai Indians,Runs,1.0,NaN,JJ Bumrah,"['Q de Kock', 'RG Sharma', 'SA Yadav', 'Ishan ...","['F du Plessis', 'SR Watson', 'SK Raina', 'AT ...",IJ Gould,Nitin Menon
254,1136620,Mumbai,2018-05-27,2018,Final,Sunrisers Hyderabad,Chennai Super Kings,Wankhede Stadium,Chennai Super Kings,field,N,Chennai Super Kings,Wickets,8.0,NaN,SR Watson,"['SP Goswami', 'S Dhawan', 'KS Williamson', 'S...","['SR Watson', 'F du Plessis', 'SK Raina', 'AT ...",M Erasmus,S Ravi
314,1082650,Hyderabad,2017-05-21,2017,Final,Mumbai Indians,Rising Pune Supergiant,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,bat,N,Mumbai Indians,Runs,1.0,NaN,KH Pandya,"['LMP Simmons', 'PA Patel', 'AT Rayudu', 'RG S...","['AM Rahane', 'RA Tripathi', 'SPD Smith', 'MS ...",NJ Llong,S Ravi
373,981019,Bangalore,2016-05-29,2016,Final,Royal Challengers Bangalore,Sunrisers Hyderabad,M Chinnaswamy Stadium,Sunrisers Hyderabad,bat,N,Sunrisers Hyderabad,Runs,8.0,NaN,BCJ Cutting,"['CH Gayle', 'V Kohli', 'AB de Villiers', 'KL ...","['DA Warner', 'S Dhawan', 'MC Henriques', 'Yuv...",HDPK Dharmasena,BNJ Oxenford
433,829823,Kolkata,2015-05-24,2015,Final,Mumbai Indians,Chennai Super Kings,Eden Gardens,Chennai Super Kings,field,N,Mumbai Indians,Runs,41.0,NaN,RG Sharma,"['LMP Simmons', 'PA Patel', 'RG Sharma', 'KA P...","['DR Smith', 'MEK Hussey', 'SK Raina', 'MS Dho...",HDPK Dharmasena,RK Illingworth
492,734049,Bangalore,2014-06-01,2014,Final,Kolkata Knight Riders,Kings XI Punjab,M Chinnaswamy Stadium,Kolkata Knight Riders,field,N,Kolkata Knight Riders,Wickets,3.0,NaN,MK Pandey,"['RV Uthappa', 'G Gambhir', 'MK Pandey', 'YK P...","['V Sehwag', 'M Vohra', 'GJ Bailey', 'WP Saha'...",HDPK Dharmasena,BNJ Oxenford
552,598073,Kolkata,2013-05-26,2013,Final,Chennai Super Kings,Mumbai Indians,Eden Gardens,Mumbai Indians,bat,N,Mumbai Indians,Runs,23.0,NaN,KA Pollard,"['MEK Hussey', 'M Vijay', 'SK Raina', 'S Badri...","['DR Smith', 'AP Tare', 'KD Karthik', 'RG Shar...",HDPK Dharmasena,SJA Taufel
628,548381,Chennai,2012-05-27,2012,Final,Kolkata Knight Riders,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk",Chennai Super Kings,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,MS Bisla,"['MS Bisla', 'G Gambhir', 'JH Kallis', 'LR Shu...","['MEK Hussey', 'M Vijay', 'SK Raina', 'MS Dhon...",BF Bowden,SJA Taufel
702,501271,Chennai,2011-05-28,2011,Final,Chennai Super Kings,Royal Challengers Bangalore,"MA Chidambaram Stadium, Chepauk",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,58.0,NaN,M Vijay,"['MEK Hussey', 'M Vijay', 'MS Dhoni', 'SK Rain...","['MA Agarwal', 'CH Gayle', 'V Kohli', 'AB de V...",Asad Rauf,SJA Taufel
775,419165,Mumbai,2010-04-25,2009/10,Final,Chennai Super Kings,Mumbai Indians,Dr DY Patil Sports Academy,Chennai Super Kings,bat,N,Chennai Super Kings,Runs,22.0,NaN,SK Raina,"['M Vijay', 'ML Hayden', 'SK Raina', 'S Badrin...","['S Dhawan', 'SR Tendulkar', 'AM Nayar', 'Harb...",RE Koertzen,SJA Taufel
835,392239,Johannesburg,2009-05-24,2009,Final,Royal Challengers Bangalore,Deccan Chargers,New Wanderers Stadium,Royal Challengers Bangalore,field,N,Deccan Chargers,Runs,6.0,NaN,A Kumble,"['JH Kallis', 'MK Pandey', 'RE van der Merwe',...","['AC Gilchrist', 'HH Gibbs', 'TL Suman', 'A Sy...",RE Koertzen,SJA Taufel
892,336040,Mumbai,2008-06-01,2007/08,Final,Chennai Super Kings,Rajasthan Royals,Dr DY Patil Sports Academy,Rajasthan Royals,field,N,Rajasthan Royals,Wickets,3.0,NaN,YK Pathan,"['PA Patel', 'S Vidyut', 'SK Raina', 'JA Morke...","['NK Patel', 'SA Asnodkar', 'Kamran Akmal', 'S...",BF Bowden,RE Koertzen

In [32]:
#how many super over finishes have occured
ipl_data[ipl_data["SuperOver"]=='Y'].shape[0]

14

In [33]:
#find how many matches has csk won in kolkata
ipl_data[(ipl_data['WinningTeam']=='Chennai Super Kings') & (ipl_data['City']=='Kolkata')].shape[0]

5

In [34]:
#toss winner is match winner in percenat
(ipl_data[(ipl_data['TossWinner']==ipl_data['WinningTeam'])].shape[0])/ipl_data.shape[0]*100

51.473684210526315

# Adding new cols

In [35]:
#completely new
data['Country']='India'
data.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,Country
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished,India
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished,India
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished,India
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished,India
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished,India

# Lets save some memory :)

In [36]:
ipl_data["ID"]=ipl_data["ID"].astype('int32')

In [37]:
#categorical variables column to dtype as category
ipl_data["Team1"]=ipl_data["Team1"].astype('category')
ipl_data["Team2"]=ipl_data["Team2"].astype('category')
ipl_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int32
 1   City             899 non-null    object
 2   Date             950 non-null    object
 3   year             950 non-null    object
 4   MatchNumber      950 non-null    object
 5   Team1            950 non-null    category
 6   Team2            950 non-null    category
 7   Venue            950 non-null    object
 8   TossWinner       950 non-null    object
 9   TossDecision     950 non-null    object
 10  SuperOver        946 non-null    object
 11  WinningTeam      946 non-null    object
 12  WonBy            950 non-null    object
 13  Margin           932 non-null    float64
 14  method           19 non-null     object
 15  Player_of_Match  946 non-null    object
 16  Team1Players     950 non-null    object
 17  Team2Players     950 non-null    object
 18  Umpire1          950 non-null    object
 19  Umpire2          950 non-null    object
dtypes: category(2), float64(1), int32(1), object(16)
memory usage: 133.2+ KB

# **Most important functions....**

In [38]:
#value_counts
data['price'].value_counts()

price
3500000     17
4200000     17
4900000     12
3150000      9
5600000      9
            ..
6580000      1
4319000      1
4375000      1
4382000      1
13300000     1
Name: count, Length: 219, dtype: int64

In [39]:
ipl_data[~ipl_data['MatchNumber'].str.isdigit()]['Player_of_Match'].value_counts()

Player_of_Match
KA Pollard           3
F du Plessis         3
SK Raina             3
A Kumble             2
MK Pandey            2
YK Pathan            2
M Vijay              2
JJ Bumrah            2
AB de Villiers       2
SR Watson            2
HH Pandya            1
Harbhajan Singh      1
A Nehra              1
V Sehwag             1
UT Yadav             1
MS Bisla             1
BJ Hodge             1
MEK Hussey           1
MS Dhoni             1
CH Gayle             1
MM Patel             1
DE Bollinger         1
AC Gilchrist         1
RG Sharma            1
DA Warner            1
MC Henriques         1
JC Buttler           1
RM Patidar           1
DA Miller            1
VR Iyer              1
SP Narine            1
RD Gaikwad           1
TA Boult             1
MP Stoinis           1
KS Williamson        1
RR Pant              1
SA Yadav             1
Rashid Khan          1
AD Russell           1
KH Pandya            1
KV Sharma            1
NM Coulter-Nile      1
Washington Sundar    1
BCJ Cutting          1
M Ntini              1
Name: count, dtype: int64

In [41]:
#find which player has won the potm-->in finals and qualifiers
ipl_data[(ipl_data['MatchNumber']=='Final') | (ipl_data['MatchNumber']==[['Qualifier 1 ','Qualifier 2']])]['Player_of_Match']

ValueError: ('Lengths must match to compare', (950,), (1, 2))

In [42]:
#how many matches each team has played
(ipl_data['Team1'].value_counts()+ipl_data['Team2'].value_counts()).sort_values(ascending=False)

Mumbai Indians                 231
Royal Challengers Bangalore    226
Kolkata Knight Riders          223
Chennai Super Kings            208
Rajasthan Royals               192
Kings XI Punjab                190
Delhi Daredevils               161
Sunrisers Hyderabad            152
Deccan Chargers                 75
Delhi Capitals                  63
Pune Warriors                   46
Gujarat Lions                   30
Punjab Kings                    28
Gujarat Titans                  16
Rising Pune Supergiant          16
Lucknow Super Giants            15
Kochi Tuskers Kerala            14
Rising Pune Supergiants         14
Name: count, dtype: int64

# sort_values(series and Df)-->ascending-->na_position-->inplace-->multiple cols

In [43]:
data['bathrooms'].sort_values()

272    1
371    1
370    1
369    1
368    1
      ..
89     3
290    3
499    3
195    3
1      4
Name: bathrooms, Length: 545, dtype: int64

In [44]:
#if in case a column has NaN values and if we try to sort it,the Nan value goes to last and remaining gets sorted above
data['parking'].sort_values(na_position='first')

544    0
274    0
457    0
543    0
271    0
      ..
225    3
472    3
331    3
93     3
247    3
Name: parking, Length: 545, dtype: int64

# rank(Series)

In [45]:
ipl_data["year"]=ipl_data['Team1'].rank(ascending=False)
ipl_data.sample(10)

,ID,City,Date,year,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
355,1082609,Hyderabad,2017-04-17,35.0,19,Sunrisers Hyderabad,Kings XI Punjab,"Rajiv Gandhi International Stadium, Uppal",Kings XI Punjab,field,N,Sunrisers Hyderabad,Runs,5.0,NaN,B Kumar,"['DA Warner', 'S Dhawan', 'MC Henriques', 'Yuv...","['HM Amla', 'M Vohra', 'GJ Maxwell', 'EJG Morg...",AY Dandekar,A Deshmukh
297,1136577,Pune,2018-04-20,895.0,17,Chennai Super Kings,Rajasthan Royals,Maharashtra Cricket Association Stadium,Rajasthan Royals,field,N,Chennai Super Kings,Runs,64.0,NaN,SR Watson,"['SR Watson', 'AT Rayudu', 'SK Raina', 'MS Dho...","['AM Rahane', 'H Klaasen', 'SV Samson', 'BA St...",KN Ananthapadmanabhan,Nitin Menon
137,1237177,NaN,2020-11-05,395.5,Qualifier 1,Mumbai Indians,Delhi Capitals,Dubai International Cricket Stadium,Delhi Capitals,field,N,Mumbai Indians,Runs,57.0,NaN,JJ Bumrah,"['Q de Kock', 'RG Sharma', 'SA Yadav', 'Ishan ...","['PP Shaw', 'S Dhawan', 'AM Rahane', 'SS Iyer'...",CB Gaffaney,Nitin Menon
428,980909,Kolkata,2016-04-13,512.0,5,Kolkata Knight Riders,Mumbai Indians,Eden Gardens,Mumbai Indians,field,N,Mumbai Indians,Wickets,6.0,NaN,RG Sharma,"['RV Uthappa', 'G Gambhir', 'MK Pandey', 'AD R...","['RG Sharma', 'PA Patel', 'HH Pandya', 'MJ McC...",Nitin Menon,S Ravi
878,392196,Durban,2009-04-27,895.0,16,Chennai Super Kings,Deccan Chargers,Kingsmead,Deccan Chargers,field,N,Deccan Chargers,Wickets,6.0,NaN,HH Gibbs,"['PA Patel', 'ML Hayden', 'SK Raina', 'MS Dhon...","['AC Gilchrist', 'HH Gibbs', 'VVS Laxman', 'RG...",IL Howell,TH Wijewardene
398,980969,Bangalore,2016-05-07,132.5,35,Royal Challengers Bangalore,Rising Pune Supergiants,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Royal Challengers Bangalore,Wickets,7.0,NaN,V Kohli,"['V Kohli', 'KL Rahul', 'AB de Villiers', 'SR ...","['AM Rahane', 'UT Khawaja', 'SS Tiwary', 'MS D...",CB Gaffaney,BNJ Oxenford
220,1178409,Delhi,2019-04-18,395.5,34,Mumbai Indians,Delhi Capitals,Arun Jaitley Stadium,Mumbai Indians,bat,N,Mumbai Indians,Runs,40.0,NaN,HH Pandya,"['RG Sharma', 'Q de Kock', 'BCJ Cutting', 'SA ...","['PP Shaw', 'S Dhawan', 'C Munro', 'SS Iyer', ...",BNJ Oxenford,NJ Llong
99,1254113,Sharjah,2021-09-24,132.5,35,Royal Challengers Bangalore,Chennai Super Kings,Sharjah Cricket Stadium,Chennai Super Kings,field,N,Chennai Super Kings,Wickets,6.0,NaN,DJ Bravo,"['V Kohli', 'D Padikkal', 'AB de Villiers', 'G...","['RD Gaikwad', 'F du Plessis', 'MM Ali', 'AT R...",AK Chaudhary,Nitin Menon
102,1254111,Dubai,2021-09-21,254.0,32,Rajasthan Royals,Punjab Kings,Dubai International Cricket Stadium,Punjab Kings,field,N,Rajasthan Royals,Runs,2.0,NaN,Kartik Tyagi,"['E Lewis', 'YBK Jaiswal', 'SV Samson', 'LS Li...","['KL Rahul', 'MA Agarwal', 'AK Markram', 'N Po...",AK Chaudhary,MA Gough
29,1304091,Mumbai,2022-05-01,455.5,45,Lucknow Super Giants,Delhi Capitals,"Wankhede Stadium, Mumbai",Lucknow Super Giants,bat,N,Lucknow Super Giants,Runs,6.0,NaN,Mohsin Khan,"['Q de Kock', 'KL Rahul', 'DJ Hooda', 'MP Stoi...","['PP Shaw', 'DA Warner', 'MR Marsh', 'RR Pant'...",Chirra Ravikanthreddy,CB Gaffaney

## Sort_index(series and DF)

In [46]:
marks={
    "maths":67,
    "english":98,
    "science":87,
    "hindi":67,
    "telugu":77
}
marks_df=pd.Series(marks)
marks_df

maths      67
english    98
science    87
hindi      67
telugu     77
dtype: int64

In [47]:
marks_df.sort_index()

english    98
hindi      67
maths      67
science    87
telugu     77
dtype: int64

# set_index(dataframe)-->inplace

In [48]:
ipl_data.set_index('City',inplace=True)
ipl_data

,ID,Date,year,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
City,,,,,,,,,,,,,,,,,,,
Ahmedabad,1312200,2022-05-29,254.0,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
Ahmedabad,1312199,2022-05-27,132.5,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
Kolkata,1312198,2022-05-25,132.5,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
Kolkata,1312197,2022-05-24,254.0,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
Mumbai,1304116,2022-05-22,35.0,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Kolkata,335986,2008-04-20,512.0,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
Mumbai,335985,2008-04-20,395.5,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
Delhi,335984,2008-04-19,729.0,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
Chandigarh,335983,2008-04-19,617.5,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
Bangalore,335982,2008-04-18,132.5,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

# Reset Index(Series+DF)-->drop parameter

In [49]:
ipl_data.reset_index(inplace=True)

In [50]:
ipl_data

,City,ID,Date,year,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,Ahmedabad,1312200,2022-05-29,254.0,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,Ahmedabad,1312199,2022-05-27,132.5,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,Kolkata,1312198,2022-05-25,132.5,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,Kolkata,1312197,2022-05-24,254.0,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,Mumbai,1304116,2022-05-22,35.0,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,Kolkata,335986,2008-04-20,512.0,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,Mumbai,335985,2008-04-20,395.5,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,Delhi,335984,2008-04-19,729.0,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,Chandigarh,335983,2008-04-19,617.5,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,Bangalore,335982,2008-04-18,132.5,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

# Series to DF using reset_index()

In [51]:
marks_df.reset_index()
type(marks_df.reset_index())

pandas.core.frame.DataFrame

# rename(DF)-->index

In [52]:
ipl_data.set_index('Date',inplace=True)
ipl_data

,City,ID,year,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
Date,,,,,,,,,,,,,,,,,,,
2022-05-29,Ahmedabad,1312200,254.0,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
2022-05-27,Ahmedabad,1312199,132.5,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2022-05-25,Kolkata,1312198,132.5,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
2022-05-24,Kolkata,1312197,254.0,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
2022-05-22,Mumbai,1304116,35.0,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2008-04-20,Kolkata,335986,512.0,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
2008-04-20,Mumbai,335985,395.5,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
2008-04-19,Delhi,335984,729.0,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
2008-04-19,Chandigarh,335983,617.5,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
2008-04-18,Bangalore,335982,132.5,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [53]:
ipl_data.rename(columns={"Team1":"HomeTeam"},inplace=True)
ipl_data

,City,ID,year,MatchNumber,HomeTeam,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
Date,,,,,,,,,,,,,,,,,,,
2022-05-29,Ahmedabad,1312200,254.0,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
2022-05-27,Ahmedabad,1312199,132.5,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2022-05-25,Kolkata,1312198,132.5,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
2022-05-24,Kolkata,1312197,254.0,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
2022-05-22,Mumbai,1304116,35.0,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2008-04-20,Kolkata,335986,512.0,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
2008-04-20,Mumbai,335985,395.5,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
2008-04-19,Delhi,335984,729.0,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
2008-04-19,Chandigarh,335983,617.5,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
2008-04-18,Bangalore,335982,132.5,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [54]:
#changing index
ipl_data.rename(index={"2022-05-29":"29/05/2022"},inplace=True)
ipl_data

,City,ID,year,MatchNumber,HomeTeam,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
Date,,,,,,,,,,,,,,,,,,,
29/05/2022,Ahmedabad,1312200,254.0,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
2022-05-27,Ahmedabad,1312199,132.5,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2022-05-25,Kolkata,1312198,132.5,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
2022-05-24,Kolkata,1312197,254.0,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
2022-05-22,Mumbai,1304116,35.0,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2008-04-20,Kolkata,335986,512.0,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
2008-04-20,Mumbai,335985,395.5,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
2008-04-19,Delhi,335984,729.0,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
2008-04-19,Chandigarh,335983,617.5,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
2008-04-18,Bangalore,335982,132.5,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

# Unique(series)

In [55]:
ipl_data['City'].unique()

array(['Ahmedabad', 'Kolkata', 'Mumbai', 'Navi Mumbai', 'Pune', 'Dubai',
       'Sharjah', 'Abu Dhabi', 'Delhi', 'Chennai', nan, 'Hyderabad',
       'Visakhapatnam', 'Chandigarh', 'Bengaluru', 'Jaipur', 'Indore',
       'Bangalore', 'Kanpur', 'Rajkot', 'Raipur', 'Ranchi', 'Cuttack',
       'Dharamsala', 'Kochi', 'Nagpur', 'Johannesburg', 'Centurion',
       'Durban', 'Bloemfontein', 'Port Elizabeth', 'Kimberley',
       'East London', 'Cape Town'], dtype=object)

# nUnique(Series+DF)

In [56]:
ipl_data.nunique()

City                33
ID                 950
year                18
MatchNumber         80
HomeTeam            18
Team2               18
Venue               49
TossWinner          18
TossDecision         2
SuperOver            2
WinningTeam         18
WonBy                4
Margin              94
method               1
Player_of_Match    262
Team1Players       932
Team2Players       937
Umpire1             58
Umpire2             60
dtype: int64

# isnull(series+DF)

In [57]:
ipl_data.isnull().sum()

City                51
ID                   0
year                 0
MatchNumber          0
HomeTeam             0
Team2                0
Venue                0
TossWinner           0
TossDecision         0
SuperOver            4
WinningTeam          4
WonBy                0
Margin              18
method             931
Player_of_Match      4
Team1Players         0
Team2Players         0
Umpire1              0
Umpire2              0
dtype: int64

# notnull(series+DF)

In [58]:
ipl_data.notnull().sum()

City               899
ID                 950
year               950
MatchNumber        950
HomeTeam           950
Team2              950
Venue              950
TossWinner         950
TossDecision       950
SuperOver          946
WinningTeam        946
WonBy              950
Margin             932
method              19
Player_of_Match    946
Team1Players       950
Team2Players       950
Umpire1            950
Umpire2            950
dtype: int64

# hasnans(series+DF)

In [59]:
ipl_data['SuperOver'].hasnans

True

# dropna(series+DF)-->how parameter-->

In [60]:
ipl_data.isnull().sum()

City                51
ID                   0
year                 0
MatchNumber          0
HomeTeam             0
Team2                0
Venue                0
TossWinner           0
TossDecision         0
SuperOver            4
WinningTeam          4
WonBy                0
Margin              18
method             931
Player_of_Match      4
Team1Players         0
Team2Players         0
Umpire1              0
Umpire2              0
dtype: int64

In [61]:
ipl_data.isnull().sum()

City                51
ID                   0
year                 0
MatchNumber          0
HomeTeam             0
Team2                0
Venue                0
TossWinner           0
TossDecision         0
SuperOver            4
WinningTeam          4
WonBy                0
Margin              18
method             931
Player_of_Match      4
Team1Players         0
Team2Players         0
Umpire1              0
Umpire2              0
dtype: int64

In [62]:
data.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
Country             0
dtype: int64

# fillna(Series + DF)

In [63]:
ipl_data["method"].fillna("Match uninterrupted",inplace=True)
ipl_data["method"].isnull().sum()

0

In [65]:
print(ipl_data["Margin"].isnull().sum())
ipl_data["Margin"].fillna(ipl_data["Margin"].mean(),inplace=True)
print(ipl_data["Margin"].isnull().sum())

18
0

In [76]:
#ffill-to replace missing values with next values
print(ipl_data["Player_of_Match"].fillna(method='ffill',inplace=True))
print(ipl_data["Player_of_Match"].sample(13))

None
Date
2022-04-11      KS Williamson
2009-05-10           A Mishra
2019-04-15         SL Malinga
2021-04-14         GJ Maxwell
2018-04-11          SV Samson
2012-05-10      BW Hilfenhaus
2012-04-06          AM Rahane
2008-04-18        BB McCullum
2021-04-13          RD Chahar
2016-05-07         MP Stoinis
2009-05-12    Harbhajan Singh
2018-05-23         AD Russell
2013-04-13          RG Sharma
Name: Player_of_Match, dtype: object

<ipython-input-76-ffa73d79d5fa>:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  print(ipl_data["Player_of_Match"].fillna(method='ffill',inplace=True))

In [79]:
#bfill-to replace null values with its before values
print(ipl_data["Player_of_Match"].fillna(method='bfill',inplace=True))
print(ipl_data["Player_of_Match"].sample(13))

None
Date
2018-04-07            DJ Bravo
2009-05-09    DPMD Jayawardene
2010-03-30          SL Malinga
2020-10-24           CJ Jordan
2020-10-22           MK Pandey
2009-05-03           JH Kallis
2017-05-05      Sandeep Sharma
2017-04-20          JC Buttler
2022-04-24            KL Rahul
2011-04-24          SL Malinga
2019-04-04         JM Bairstow
2016-04-24            SA Yadav
2013-05-19            PA Patel
Name: Player_of_Match, dtype: object

<ipython-input-79-95ded1aea1ac>:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  print(ipl_data["Player_of_Match"].fillna(method='bfill',inplace=True))

# Drop_dupliactes()

In [82]:
a=pd.Series([1,2,3,1,1,2,3,4,5,6,7,7,8,6,4,5,9,10])
print(a)

0      1
1      2
2      3
3      1
4      1
5      2
6      3
7      4
8      5
9      6
10     7
11     7
12     8
13     6
14     4
15     5
16     9
17    10
dtype: int64

In [83]:
a.duplicated().sum()

8

In [85]:
print(a.drop_duplicates(inplace=True))
print(a.duplicated().sum())

None
0

In [86]:
#Parameters
#keep='first'
#keep='last'

# #find the last match played by vk in delhi

In [88]:

ipl_data["all players"]=ipl_data["Team1Players"]+ipl_data["Team2Players"]
ipl_data.head()

,City,ID,year,MatchNumber,HomeTeam,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2,all players
Date,,,,,,,,,,,,,,,,,,,,
29/05/2022,Ahmedabad,1312200,254.0,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,Match uninterrupted,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ..."
2022-05-27,Ahmedabad,1312199,132.5,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,Match uninterrupted,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ..."
2022-05-25,Kolkata,1312198,132.5,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,Match uninterrupted,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ..."
2022-05-24,Kolkata,1312197,254.0,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,Match uninterrupted,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ..."
2022-05-22,Mumbai,1304116,35.0,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,Match uninterrupted,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ..."

In [99]:
def did_kohli_play(players_list):
  return 'V Kohli' in players_list

In [100]:
ipl_data["Did kohli play"]=ipl_data["all players"].apply(did_kohli_play)

In [101]:
ipl_data

,City,ID,year,MatchNumber,HomeTeam,Team2,Venue,TossWinner,TossDecision,SuperOver,...,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2,all players,Did kohli play
Date,,,,,,,,,,,,,,,,,,,,,
29/05/2022,Ahmedabad,1312200,254.0,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,...,Wickets,7.0,Match uninterrupted,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",False
2022-05-27,Ahmedabad,1312199,132.5,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,...,Wickets,7.0,Match uninterrupted,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...",True
2022-05-25,Kolkata,1312198,132.5,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,...,Runs,14.0,Match uninterrupted,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...",True
2022-05-24,Kolkata,1312197,254.0,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,...,Wickets,7.0,Match uninterrupted,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",False
2022-05-22,Mumbai,1304116,35.0,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,...,Wickets,5.0,Match uninterrupted,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...",False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2008-04-20,Kolkata,335986,512.0,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,...,Wickets,5.0,Match uninterrupted,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...",False
2008-04-20,Mumbai,335985,395.5,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,...,Wickets,5.0,Match uninterrupted,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...",True
2008-04-19,Delhi,335984,729.0,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,...,Wickets,9.0,Match uninterrupted,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...",False
2008-04-19,Chandigarh,335983,617.5,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,...,Runs,33.0,Match uninterrupted,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...",False
2008-04-18,Bangalore,335982,132.5,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,...,Runs,140.0,Match uninterrupted,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...",True

In [98]:
ipl_data["all players"]

Date
29/05/2022    ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...
2022-05-27    ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...
2022-05-25    ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...
2022-05-24    ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...
2022-05-22    ['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...
                                    ...
2008-04-20    ['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...
2008-04-20    ['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...
2008-04-19    ['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...
2008-04-19    ['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...
2008-04-18    ['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...
Name: all players, Length: 950, dtype: object

In [104]:
ipl_data[(ipl_data["Did kohli play"]==True) & (ipl_data["City"]=="Delhi")].drop_duplicates(subset=["City","Did kohli play"],keep="first")

,City,ID,year,MatchNumber,HomeTeam,Team2,Venue,TossWinner,TossDecision,SuperOver,...,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2,all players,Did kohli play
Date,,,,,,,,,,,,,,,,,,,,,
2019-04-28,Delhi,1178421,786.0,46,Delhi Capitals,Royal Challengers Bangalore,Arun Jaitley Stadium,Delhi Capitals,bat,N,...,Runs,16.0,Match uninterrupted,S Dhawan,"['PP Shaw', 'S Dhawan', 'SS Iyer', 'RR Pant', ...","['PA Patel', 'V Kohli', 'AB de Villiers', 'S D...",BNJ Oxenford,KN Ananthapadmanabhan,"['PP Shaw', 'S Dhawan', 'SS Iyer', 'RR Pant', ...",True

# drop(series+DF)

In [106]:
b=pd.Series([10,2,3,4,18,19,23,67,17])
b

0    10
1     2
2     3
3     4
4    18
5    19
6    23
7    67
8    17
dtype: int64

In [107]:
#drop rows
b.drop(index=[3,7])

0    10
1     2
2     3
4    18
5    19
6    23
8    17
dtype: int64

In [108]:
#drop columns
ipl_data.drop(columns=["Team1Players","Team2Players"])

,City,ID,year,MatchNumber,HomeTeam,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Umpire1,Umpire2,all players,Did kohli play
Date,,,,,,,,,,,,,,,,,,,
29/05/2022,Ahmedabad,1312200,254.0,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,Match uninterrupted,HH Pandya,CB Gaffaney,Nitin Menon,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",False
2022-05-27,Ahmedabad,1312199,132.5,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,Match uninterrupted,JC Buttler,CB Gaffaney,Nitin Menon,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...",True
2022-05-25,Kolkata,1312198,132.5,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,Match uninterrupted,RM Patidar,J Madanagopal,MA Gough,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...",True
2022-05-24,Kolkata,1312197,254.0,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,Match uninterrupted,DA Miller,BNJ Oxenford,VK Sharma,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",False
2022-05-22,Mumbai,1304116,35.0,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,Match uninterrupted,Harpreet Brar,AK Chaudhary,NA Patwardhan,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...",False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2008-04-20,Kolkata,335986,512.0,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,Match uninterrupted,DJ Hussey,BF Bowden,K Hariharan,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...",False
2008-04-20,Mumbai,335985,395.5,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,Match uninterrupted,MV Boucher,SJ Davis,DJ Harper,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...",True
2008-04-19,Delhi,335984,729.0,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,Match uninterrupted,MF Maharoof,Aleem Dar,GA Pratapkumar,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...",False
2008-04-19,Chandigarh,335983,617.5,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,Match uninterrupted,MEK Hussey,MR Benson,SL Shastri,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...",False
2008-04-18,Bangalore,335982,132.5,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,Match uninterrupted,BB McCullum,Asad Rauf,RE Koertzen,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...",True

# apply(Series+DF)

In [109]:
temp=pd.Series([1,2,3,4,5])
def square(x):
  return x**2
temp.apply(square)

0     1
1     4
2     9
3    16
4    25
dtype: int64

In [111]:
points_df=pd.DataFrame({
    '1st point':[(3,4),(-6,5),[0,0],[-10,1],[4,5]],
    '2nd point':[(4,3),(5,-6),[0,1],[1,-10],[5,4]]
})
points_df

  1st point 2nd point
0    (3, 4)    (4, 3)
1   (-6, 5)   (5, -6)
2    [0, 0]    [0, 1]
3  [-10, 1]  [1, -10]
4    [4, 5]    [5, 4]

In [112]:
def euclidiean(row):
  pt_a=row['1st point']
  pt_b=row['2nd point']
  return ((pt_a[0]-pt_b[0])**2+(pt_a[1]-pt_b[1])**2)**0.5

In [114]:
points_df["Distance"]=points_df.apply(euclidiean,axis=1)
points_df

  1st point 2nd point   Distance
0    (3, 4)    (4, 3)   1.000000
1   (-6, 5)   (5, -6)  11.000000
2    [0, 0]    [0, 1]   1.414214
3  [-10, 1]  [1, -10]  11.000000
4    [4, 5]    [5, 4]   1.000000